=== olimpiab97-cmyk/randle-system/Architecture/Audits/2026-07-21_Current_Production_Baseline_Capture_Boundary_Specification_DRAFT/comparison_authority_R5_schema_DRAFT.json
{"$id":"urn:randle:r5:comparison_authority","$schema":"https://json-schema.org/draft/2020-12/schema","additionalProperties":false,"properties":{"authority_id":{"const":"R5-MEASURED-COMPARATOR"},"comparator_git_blob":{"const":"f559dc9e65c8ce63f47eb9b2875c9712fc6aac77"},"comparator_raw_sha256":{"const":"84438891142345e22c4b6e6fdf5c4d2a0050affb0209426566a0db6f35e9a725"},"environment_identity":{"const":"6e8885a54ca6196a99061fa7ae43e65d3c1ad4ad4d4684ad93ebfc97a05d927a"},"expectation_identity":{"const":"ef50fbb5963986a0e031f84d06fa0d2313432ccd8e838d2540262dc8d6746f2b"},"interface_version":{"const":"RANDLE-R5-COMPARATOR-1"},"issuance_authority":{"const":"R5-COMPARISON-ISSUER"},"observation_identity":{"const":"d3025a12d4f572c11a5fe70ab5fad1b77c4791aeb42af67d3ba52eeba1768498"},"python_executable_identity":{"const":"9b0bffb7a259cd2722df454fdfff41ee13665820cff1f578b1d97d31f9ef93d5"},"result_schema":{"const":"terminal_comparison_receipt_R5_schema_DRAFT.json"},"schema_version":{"const":"7.0.0-DRAFT"}},"required":["schema_version","authority_id","comparator_git_blob","comparator_raw_sha256","interface_version","python_executable_identity","environment_identity","expectation_identity","observation_identity","result_schema","issuance_authority"],"type":"object"}

=== olimpiab97-cmyk/randle-system/Architecture/Audits/2026-07-21_Current_Production_Baseline_Capture_Boundary_Specification_DRAFT/comparison_authority_R5_DRAFT.json
{"authority_id":"R5-MEASURED-COMPARATOR","comparator_git_blob":"f559dc9e65c8ce63f47eb9b2875c9712fc6aac77","comparator_raw_sha256":"84438891142345e22c4b6e6fdf5c4d2a0050affb0209426566a0db6f35e9a725","environment_identity":"6e8885a54ca6196a99061fa7ae43e65d3c1ad4ad4d4684ad93ebfc97a05d927a","expectation_identity":"ef50fbb5963986a0e031f84d06fa0d2313432ccd8e838d2540262dc8d6746f2b","interface_version":"RANDLE-R5-COMPARATOR-1","issuance_authority":"R5-COMPARISON-ISSUER","observation_identity":"d3025a12d4f572c11a5fe70ab5fad1b77c4791aeb42af67d3ba52eeba1768498","python_executable_identity":"9b0bffb7a259cd2722df454fdfff41ee13665820cff1f578b1d97d31f9ef93d5","result_schema":"terminal_comparison_receipt_R5_schema_DRAFT.json","schema_version":"7.0.0-DRAFT"}
